version: 2

sources:
  - name: raw
    database: ak-data-warehouse
    schema: raw_data
    tables:
      - name: users_raw
        description: "Dummy users table for testing"
      - name: settlement_events
        description: "payment_db settlement events table"
        config:
          loaded_at_field: ingested_at
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}
      - name: journal_entries
        description: "netsuite journal entries table"
        config:
          loaded_at_field: ingested_at
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}
      - name: merchants
        description: "merchants table"
        config:
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}

